import { MenuItem } from './types';

// =====================================================
// DEMO DATA - Yeh tab use hota hai jab Google Sheet
// connect nahi hai. Aap Google Sheet se real data
// fetch kar sakte hain - neeche guide hai.
// =====================================================

export const DEMO_MENU_ITEMS: MenuItem[] = [
  // ===== BREAKFAST =====
  {
    id: '1',
    name: 'Paratha with Egg',
    description: 'Crispy layered paratha served with fried egg, butter and homemade achaar',
    price: 120,
    calories: 450,
    portionSize: '2 Parathas + 1 Egg',
    category: 'Breakfast',
    imageUrl: '/images/breakfast.jpg',
    isAvailable: true,
    isSpecial: true,
    allergens: 'Gluten, Egg, Dairy',
    prepTime: '10 mins',
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Halwa Puri',
    description: 'Traditional halwa puri with cholay and aloo bhujia - weekend special',
    price: 180,
    calories: 620,
    portionSize: '2 Puris + Full Plate',
    category: 'Breakfast',
    imageUrl: '/images/breakfast.jpg',
    isAvailable: true,
    isSpecial: false,
    allergens: 'Gluten, Dairy',
    prepTime: '5 mins',
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Chai + Biscuit',
    description: 'Hot Doodh Patti chai with 4 biscuits',
    price: 50,
    calories: 180,
    portionSize: '1 Cup + 4 Biscuits',
    category: 'Breakfast',
    imageUrl: '/images/refreshment.jpg',
    isAvailable: true,
    isSpecial: false,
    allergens: 'Dairy, Gluten',
    prepTime: '5 mins',
    rating: 4.7,
  },

  // ===== MORNING REFRESHMENT =====
  {
    id: '4',
    name: 'Samosa (2 pcs)',
    description: 'Crispy golden samosas with imli chutney and green chutney',
    price: 60,
    calories: 280,
    portionSize: '2 Pieces',
    category: 'Morning Refreshment',
    imageUrl: '/images/refreshment.jpg',
    isAvailable: true,
    isSpecial: false,
    allergens: 'Gluten',
    prepTime: '3 mins',
    rating: 4.6,
  },
  {
    id: '5',
    name: 'Pakora Platter',
    description: 'Mixed vegetable pakoras - aloo, pyaz, palak - served hot',
    price: 80,
    calories: 320,
    portionSize: '8-10 Pieces',
    category: 'Morning Refreshment',
    imageUrl: '/images/refreshment.jpg',
    isAvailable: true,
    isSpecial: true,
    allergens: 'Gluten, Chickpea',
    prepTime: '7 mins',
    rating: 4.5,
  },
  {
    id: '6',
    name: 'Cold Coffee',
    description: 'Chilled blended coffee with milk and ice cream scoop',
    price: 150,
    calories: 220,
    portionSize: '350ml Glass',
    category: 'Morning Refreshment',
    imageUrl: '/images/refreshment.jpg',
    isAvailable: true,
    isSpecial: false,
    allergens: 'Dairy',
    prepTime: '5 mins',
    rating: 4.8,
  },

  // ===== LUNCH =====
  {
    id: '7',
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice cooked with tender chicken, whole spices and saffron',
    price: 280,
    calories: 750,
    portionSize: '1 Full Plate (400g)',
    category: 'Lunch',
    imageUrl: '/images/lunch.jpg',
    isAvailable: true,
    isSpecial: true,
    allergens: 'None',
    prepTime: '2 mins',
    rating: 4.9,
  },
  {
    id: '8',
    name: 'Dal Chawal',
    description: 'Creamy masoor dal with steamed basmati rice, served with achaar',
    price: 160,
    calories: 520,
    portionSize: '1 Bowl Dal + 1 Plate Rice',
    category: 'Lunch',
    imageUrl: '/images/lunch.jpg',
    isAvailable: true,
    isSpecial: false,
    allergens: 'None',
    prepTime: '3 mins',
    rating: 4.4,
  },
  {
    id: '9',
    name: 'Chapli Kabab + Naan',
    description: 'Spicy minced beef kabab served with tandoori naan and raita',
    price: 250,
    calories: 680,
    portionSize: '2 Kababs + 1 Naan',
    category: 'Lunch',
    imageUrl: '/images/lunch.jpg',
    isAvailable: true,
    isSpecial: false,
    allergens: 'Gluten, Dairy',
    prepTime: '5 mins',
    rating: 4.7,
  },

  // ===== EVENING REFRESHMENT =====
  {
    id: '10',
    name: 'Dahi Bhalla',
    description: 'Soft lentil dumplings in creamy yogurt with sweet & spicy chutneys',
    price: 100,
    calories: 290,
    portionSize: '3 Pieces',
    category: 'Evening Refreshment',
    imageUrl: '/images/refreshment.jpg',
    isAvailable: true,
    isSpecial: true,
    allergens: 'Dairy, Lentils',
    prepTime: '3 mins',
    rating: 4.8,
  },
  {
    id: '11',
    name: 'Fresh Juice',
    description: 'Seasonal fresh fruit juice - Orange / Mango / Strawberry',
    price: 120,
    calories: 140,
    portionSize: '300ml Glass',
    category: 'Evening Refreshment',
    imageUrl: '/images/refreshment.jpg',
    isAvailable: true,
    isSpecial: false,
    allergens: 'None',
    prepTime: '5 mins',
    rating: 4.6,
  },
  {
    id: '12',
    name: 'Chana Chaat',
    description: 'Spicy boiled chickpeas with onion, tomato, coriander and tamarind',
    price: 90,
    calories: 310,
    portionSize: '1 Bowl (200g)',
    category: 'Evening Refreshment',
    imageUrl: '/images/refreshment.jpg',
    isAvailable: true,
    isSpecial: false,
    allergens: 'Chickpea',
    prepTime: '3 mins',
    rating: 4.5,
  },

  // ===== DINNER =====
  {
    id: '13',
    name: 'Chicken Karahi',
    description: 'Juicy chicken cooked in wok with tomatoes, green chillies and fresh ginger',
    price: 350,
    calories: 820,
    portionSize: 'Half Kg Karahi',
    category: 'Dinner',
    imageUrl: '/images/dinner.jpg',
    isAvailable: true,
    isSpecial: true,
    allergens: 'None',
    prepTime: '15 mins',
    rating: 4.9,
  },
  {
    id: '14',
    name: 'Mutton Sajji',
    description: 'Traditional Balochi whole leg sajji with rice and chutney',
    price: 650,
    calories: 1100,
    portionSize: '1 Full Leg',
    category: 'Dinner',
    imageUrl: '/images/dinner.jpg',
    isAvailable: false,
    isSpecial: true,
    allergens: 'None',
    prepTime: '30 mins',
    rating: 5.0,
  },
  {
    id: '15',
    name: 'Seekh Kabab + Naan',
    description: 'Juicy minced beef seekh kababs with garlic naan and mint raita',
    price: 300,
    calories: 720,
    portionSize: '4 Kababs + 2 Naans',
    category: 'Dinner',
    imageUrl: '/images/dinner.jpg',
    isAvailable: true,
    isSpecial: false,
    allergens: 'Gluten, Dairy',
    prepTime: '10 mins',
    rating: 4.7,
  },
];
